name: deploy react app              # Workflow 이름
on:
  push:
    branches:
      - dayCourseClient

jobs:                                 
  build:                              
    runs-on: ubuntu-24.04             
    steps:                            
      - uses: actions/checkout@v4 

      - name: Check Node v
        run: node -v

      - name: Install dependencies    
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://${s3 버킷 이름} 