name: deploy node api

on:
  push:
    branches:
      - dayCourseServer

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '22.x'
        
        - name: Check Node v
          run: node -v

        - name: Install dependencies # 의존성 다운
          run: |
            cd dayCourse_server  # server 폴더로 이동
            npm ci #clean install로 node_modules와 package-lock.json 파일을 삭제했다가 npm install로 맞추는 것
        
        - name: Deploy to EC2
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.EC2_HOST }}
            REMOTE_USER: ubuntu
            APP_DIR: '/home/ubuntu/dayCourse_server'
          run: |
            eval "$(ssh-agent -s)"  # SSH 에이전트 시작
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
            ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            if [ ! -d \"$APP_DIR\" ]; then
                git clone -b dayCourseServer https://github.com/jeongyuje0ngyujeong/dayCourse.git $APP_DIR; # 특정 브랜치로 clone 진행
            else
                cd $APP_DIR && git pull origin dayCourseServer;  # 이미 존재하면 최신 코드 pull
            fi &&
            cd $APP_DIR/dayCourse_server &&     # 정확한 경로로 이동
            npm install &&
            npx pm2 restart /home/ubuntu/dayCourse_server/dayCourse_server/app.js"  # app.js 경로 오류로 인해 절대 경로 지정
          

