name: deploy react app              # Workflow 이름
on:
  push:
    branches:
      - dayCourseClient

jobs:                                 
  build:                              
    runs-on: ubuntu-24.04    
    defaults:
      run:
        working-directory: ./dayCourse_client/client         
    steps:                            
      - uses: actions/checkout@v4 

      - name: Check Node v
        run: node -v

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies    
        run: npm install

      - name: Build React App
        run: npm run build
            echo ${{ github.workspace }}


      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://daycourse-front-deploy
      