name: deploy node api

on:
  push:
    branches:
      - dayCourseServer

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '22.x'
        
        - name: Check Node v
          run: node -v

        - name: Install dependencies # 의존성 다운
          run: |
            cd dayCourse_server  # server 폴더로 이동
            npm ci #clean install로 node_modules와 package-lock.json 파일을 삭제했다가 npm install로 맞추는 것
        
        - name: Deploy to EC2
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.EC2_HOST }}
            REMOTE_USER: ubuntu
          run: |
            eval "$(ssh-agent -s)"  # SSH 에이전트 시작
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
            ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
              if [ ! -d \"$APP_DIR\" ]; then
                git clone -b dayCourseServer https://github.com/jeongyuje0ngyujeong/dayCourse.git $APP_DIR;
              fi &&
              cd $APP_DIR/dayCourse_server &&

              LOCAL_COMMIT=$(git rev-parse HEAD) &&
              REMOTE_COMMIT=$(git ls-remote origin dayCourseServer | grep HEAD | awk '{print $1}') &&
              if [ \"$LOCAL_COMMIT\" != \"$REMOTE_COMMIT\" ]; then
                git pull origin dayCourseServer &&
                npm install &&
                pm2 restart app;
              else
                echo 'Already up-to-date. No deployment needed.';
              fi"

